<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<title>QQ</title>
</head>

<body>

</body>

<meta http-equiv="refresh" content="0; url=tencent://AddContact/?fromId=50&fromSubId=1&subcmd=all&uin=77060273">

</html>

theme: jekyll-theme-cayman